### ISSUE TITLE
get_etl_temperature fails *sometimes*

### ISSUE THREAD

**Issue by Poofjunior** [AllenNeuralDynamics/TigerASI#53]
Here's the stack trace:
````
2023-08-01,15:58:04.182 INFO spim_core.spim_base.Exaspim: tile: (0, 1); stage_position: (0.000[um], 0.000[um])
2023-08-01,15:58:04.645 INFO spim_core.spim_base.Exaspim: tile data
2023-08-01,15:58:04.987 DEBUG tigerasi.tiger_controller: Sending: 'PM V?\r'
2023-08-01,15:58:06.306 DEBUG tigerasi.tiger_controller: Reply: 'V=1 :A\r\n'
2023-08-01,15:58:06.924 DEBUG tigerasi.tiger_controller: Sending: 'PM V=2\r'
2023-08-01,15:58:07.484 DEBUG tigerasi.tiger_controller: Reply: ':A\r\n'
2023-08-01,15:58:07.965 DEBUG tigerasi.tiger_controller: Sending: '35PZINFO\r'
2023-08-01,15:58:09.564 DEBUG tigerasi.tiger_controller: Reply: 'Hdwr REV.C \rV0 :24.3 V\rI'
2023-08-01,15:58:10.155 DEBUG tigerasi.tiger_controller: Sending: 'PM V=1\r'
2023-08-01,15:58:11.637 DEBUG tigerasi.tiger_controller: Reply: '2C Check> HUB[OK]\rV Mode['
XY Tiling Progress:   0%|                                                                              | 0/3 [00:42<?, ?it/s]
2023-08-01,15:58:12.319 ERROR spim_core.spim_base.Exaspim: Error raised from the main acquisition loop.
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\Github\exa-spim-control\exaspim\exaspim.py", line 316, in collect_volumetric_image
    self.log_stack_acquisition_params(self.curr_tile_index,
  File "C:\Users\Administrator\Documents\Github\exa-spim-control\exaspim\exaspim.py", line 797, in log_stack_acquisition_params
    'etl_temperature': self.tigerbox.get_etl_temp('V'),  # FIXME: this is hardcoded as V axis
  File "C:\Users\Administrator\Documents\Github\TigerASI\src\tigerasi\tiger_controller.py", line 39, in inner
    return func(self, *args, **kwds)
  File "C:\Users\Administrator\Documents\Github\TigerASI\src\tigerasi\tiger_controller.py", line 1172, in get_etl_temp
    return temp
UnboundLocalError: local variable 'temp' referenced before assignment
2023-08-01,15:58:13.498 DEBUG spim_core.devices.tiger_components.SamplePose: Absolute move to: x=0.000 y=0.000 and waiting.
2023-08-01,15:58:14.070 DEBUG tigerasi.tiger_controller: Sending: 'M Y=0 Z=0\r'
2023-08-01,15:58:15.605 DEBUG tigerasi.tiger_controller: Reply: 'IN],Tc[22.750],TCOMP['
2023-08-01,15:58:16.258 DEBUG tigerasi.tiger_controller: Sending: '/\r'
2023-08-01,15:58:17.963 DEBUG tigerasi.tiger_controller: Reply: 'ON]\rW Mode[EXT],Tc[30.0'
2023-08-01,15:58:18.838 INFO spim_core.devices.tiger_components.SamplePose: Releasing joystick control.
2023-08-01,15:58:19.289 DEBUG tigerasi.tiger_controller: Sending: 'J X+ Y+ Z+ F+ R+ M+ N+ V+ W+\r'
2023-08-01,15:58:20.890 DEBUG tigerasi.tiger_controller: Reply: '00],TCOMP[OFF]\rV> IN:127,OUT'
2023-08-01,15:58:21.482 DEBUG tigerasi.tiger_controller: Sending: 'J X=0 Y=0 Z=0 F=0 R=0 M=0 N=0 V=0 W=0\r'
2023-08-01,15:58:22.862 DEBUG tigerasi.tiger_controller: Reply: ':128 \rW> IN:1,OUT:124'
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
File ~\Documents\Github\exa-spim-control\exaspim\exaspim.py:316, in Exaspim.collect_volumetric_image(self=<exaspim.exaspim.Exaspim object>, volume_x_um=20000, volume_y_um=10000, volume_z_u
m=100, channels=[488], tile_overlap_x_percent=15, tile_overlap_y_percent=15, z_step_size_um=8, start_tile_index=0, end_tile_index=5, tile_prefix='', compressor_chunk_size=None, local_stora
ge_dir=None, img_storage_dir=None, deriv_storage_dir=None)
    315 # Log stack capture start state.
--> 316 self.log_stack_acquisition_params(self.curr_tile_index,
        self = <exaspim.exaspim.Exaspim object at 0x0000023AF4993FA0>
        self.curr_tile_index = 1
        stack_prefix = '_x_0000_y_0001_z_0000'
        z_step_size_um = 8
    317                                   stack_prefix,
    318                                   z_step_size_um)
    319 # TODO, should we do the arithmetic outside of the Camera class?
    320 # TODO, should we transfer this small file or just write directly over the network?

````

It looks like tigerasi is returning early, despite the `read_until` value being correctly set to `'\r\n'`.

**Comment by Poofjunior** [comment]
Executing `35PZINFO\r` on the TigerController software returns something unexpected:
````
Hdwr REV.C 
V0 :24.2 V
I2C Check> HUB[OK]
V Mode[EXT],Tc[22.750],TCOMP[OFF]
W Mode[EXT],Tc[30.000],TCOMP[OFF]
V> IN:128,OUT:129 
W> IN:1,OUT:124
Power Good[YES]
V> Over Current[NO] Over Temp[NO]
W> Over Current[NO] Over Temp[NO]

:A 

:A 
````
